apiVersion: v2
name: maintd
description: Spawns a set of maintenance daemons.
type: application
version: 0.2.0
appVersion: "5.11.10.1"

dependencies:
- name: common
  version: 0.1.1
  repository: "file://../common"
