# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

resetImage:
  repository: gitlab-registry.cern.ch/cta/ctageneric
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets:
    - reg-ctageneric

resetCatalogue: false

schemaVersion: ""

# This is only for the postgres pod
pod:
  extraSpec:
    # We want to know if something went wrong in CI
    restartPolicy: Never

# This can either be provided via --set-file or specified directly here
# configuration:
#   backend: "" # Can be oracle or postgres.
#   oracleConfig:
#     username: ""
#     database: ""
#     password: ""
#   postgresConfig:
#     username: ""
#     password: ""
#     server: ""
#     database: ""
