{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- $schedulerConfig := include "scheduler.config" . | fromYaml -}}
{{ range .Values.drives -}}
{{- $driveNameSlug := include "common.slugify" .name }}
{{- $tapedName := printf "%s-%s-%s" $.Release.Name "taped" $driveNameSlug | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: StatefulSet # StatefulSets enforce at most x pods semantics (in our case x=1)
metadata:
  name: {{ $tapedName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  serviceName: {{ $tapedName }}  # Ensure a headless service exists with this name; allows for stable DNS entries
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $tapedName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $tapedName }}
        {{- include "common.labels.withoutname" $ | nindent 8 }}
    spec:
      imagePullSecrets:
      {{- include "taped.imagePullSecrets" $ | nindent 6 }}
      {{- if $.Values.pod.extraSpec }}
      {{ $.Values.pod.extraSpec | toYaml | nindent 6 }}
      {{- end }}
      initContainers:
      # Required until https://github.com/kubernetes/kubernetes/issues/81089 is merged
      - name: init1-fix-sss-keytab-ownership
        image: {{ include "common.images.busybox" . }}
        imagePullPolicy: {{ include "common.images.defaultPullPolicy" . }}
        command: ["sh", "-c"]
        args:
        - |
          cp /root/sss_keytab/input/taped.keytab /root/sss_keytab/output/cta-taped.sss.keytab;
          chmod 400 /root/sss_keytab/output/cta-taped.sss.keytab;
          # Make CTA user owner (group 33 is tape)
          chown -R 1000:33 /root/sss_keytab/output/cta-taped.sss.keytab
        volumeMounts:
          - name: taped-sss-keytab
            mountPath: /root/sss_keytab/input/taped.keytab
            subPath: {{ $.Values.keytab.subPath }}
          - name: taped-sss-keytab-fixedownership
            mountPath: /root/sss_keytab/output
      containers:
      - name: "cta-taped"
        image: {{ include "taped.image" $ }}
        imagePullPolicy: {{ include "taped.imagePullPolicy" $ }}
        securityContext:
          allowPrivilegeEscalation: {{ include "common.securityContext.allowPrivilegeEscalation" $ }}
          privileged: {{ include "common.securityContext.privileged" $ }}
          capabilities:
            add:
              - SYS_RAWIO
        command: ["/bin/bash", "-c"]
        args: ["{{- if $.Values.preRun.enabled }}/scripts/pre_run.sh;{{- end }} /scripts/taped.sh; {{- if $.Values.postRun.enabled }}/scripts/post_run.sh;{{- end }}"]
        startupProbe:
          exec:
            command: ["rpm", "-q", "cta-taped"]
          initialDelaySeconds: 0
          periodSeconds: 2
          failureThreshold: 60
        readinessProbe:
          exec:
            command: ["pgrep", "-f", "/usr/bin/cta-taped"]
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        stdin: true
        env:
        - name: MY_NAME
          value: {{ $tapedName }}
        - name: MY_NAMESPACE
          value: {{ $.Release.Namespace | quote }}
        - name: INSTANCE_NAME
          value: {{ $.Release.Namespace | quote }}
        - name: MY_CONTAINER
          value: "cta-taped"
        - name: TERM
          value: "xterm"
        - name: DRIVE_NAME
          value: {{ .name }}
        - name: LIBRARY_NAME
          value: {{ .logicalLibraryName }}
        - name: DRIVE_DEVICE
          value: {{ .device }}
        - name: SCHEDULER_BACKEND
          value: {{ $schedulerConfig.backend | quote }}
        - name: XrdSecPROTOCOL
          value: sss
        - name: XrdSecSSSKT
          value: /etc/cta/cta-taped.sss.keytab
        {{- with $.Values.extraEnv }}
        {{- include "common.extraEnv" . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
        - name: cta-taped-config
          mountPath: /etc/cta/cta-taped.conf
          subPath: cta-taped.conf
        - name: catalogue-config
          mountPath: /etc/cta/cta-catalogue.conf
          subPath: cta-catalogue.conf
        {{- if eq $schedulerConfig.backend "postgres" }}
        - name: scheduler-config
          mountPath: /etc/cta/cta-scheduler.conf
          subPath: cta-scheduler.conf
        {{- else }}
        - name: scheduler-config
          mountPath: /etc/cta/cta-objectstore-tools.conf
          subPath: cta-objectstore-tools.conf
        {{- end }}
        - name: taped-sss-keytab-fixedownership
          mountPath: /etc/cta/cta-taped.sss.keytab
          subPath: cta-taped.sss.keytab
        {{- if eq $schedulerConfig.backend "ceph" }}
        - name: cta-ceph-volume
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
        - name: cta-ceph-volume
          mountPath: /etc/ceph/ceph.client.{{ $schedulerConfig.cephConfig.id }}.keyring
          subPath: ceph.client.{{ $schedulerConfig.cephConfig.id }}.keyring
        {{- end }}
        {{- if eq $schedulerConfig.backend "vfs" }}
        - name: vfs-storage-volume
          mountPath: /objectstore
        {{- end }}
        {{- if $.Values.conf.telemetry.metrics.otlp.auth.basic.passwordSecret }}
        - name: otlp-basic-auth-pwd
          mountPath: /etc/cta/otlp-basic-auth-pwd.conf
          subPath: otlp-basic-auth-pwd.conf
        {{- end }}
        {{ include "common.extraVolumeMounts" $ | nindent 8 }}
      volumes:
      - name: scripts-volume
        configMap:
          name: scripts-taped
          defaultMode: 0777
      - name: catalogue-config
        configMap:
          name: cta-catalogue-conf
      {{- if eq $schedulerConfig.backend "postgres" }}
      - name: scheduler-config
        configMap:
          name: cta-scheduler-conf
      {{- else }}
      - name: scheduler-config
        configMap:
          name: cta-objectstore-conf
      {{- end }}
      {{- if eq $schedulerConfig.backend "ceph" }}
      - name: cta-ceph-volume
        configMap:
          name: ceph-conf
      {{- end }}
      {{- if eq $schedulerConfig.backend "vfs" }}
      - name: vfs-storage-volume
        persistentVolumeClaim:
          claimName: scheduler-vfs-pvc
      {{- end }}
      - name: cta-taped-config
        configMap:
          name: cta-taped-{{ $driveNameSlug }}-conf
      - name: taped-sss-keytab
        secret:
          secretName: {{ $.Values.keytab.secretName }}
      - name: taped-sss-keytab-fixedownership
        emptyDir: {}
      {{- if $.Values.conf.telemetry.metrics.otlp.auth.basic.passwordSecret }}
      - name: otlp-basic-auth-pwd
        secret:
          secretName: {{ $.Values.conf.telemetry.metrics.otlp.auth.basic.passwordSecret }}
      {{- end }}
      {{ include "common.extraVolumes" $ | nindent 6 }}
---
{{- end }}
