{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-gen-secrets-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook-delete-policy": delete
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: secret-writer
      restartPolicy: Never
      containers:
        - name: gen-secrets
          image: {{ .Values.kerberos.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          command: ["bash", "/scripts/generate_secrets.sh"]
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
      volumes:
        - name: scripts-volume
          configMap:
            name: {{ .Release.Name }}-kdc-scripts
            defaultMode: 0777
