# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# Formatting settings for toml files
# Note that indentation is optional in toml files; it just makes things a bit more readable
[formatting]
indent_tables = true
indent_entries = true
align_entries = true
