apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-09T06:35:11Z"
  name: krb5-config
  namespace: {{.Release.Namespace}}
  labels:
    config: keypass-config
data:
  krb5.conf: |
    [libdefaults]
    default_realm = TEST.CTA

    [realms]
    TEST.CTA = {
      kdc=kdc
    }
