{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- $schedulerConfig := include "scheduler.config" $ | fromYaml -}}
{{- $allRoutines := $.Values.routines -}}
{{- range $routineName, $routineConf := $allRoutines }}
{{- if not (and (eq $routineName "garbageCollect") (eq $schedulerConfig.backend "postgres")) }}
{{- $routineNameSlug := include "common.slugify" $routineName }}
{{- $podName := printf "%s-%s-%s" $.Release.Name "rt" $routineNameSlug | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $podName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  replicas: {{ $routineConf.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $podName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $podName }}
        {{- include "common.labels.withoutname" $ | nindent 8 }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      imagePullSecrets:
      {{- include "maintd.imagePullSecrets" $ | nindent 6 }}
      {{- if $.Values.pod.extraSpec }}
      {{ $.Values.pod.extraSpec | toYaml | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init1-fix-sss-keytab-ownership
        image: {{ include "common.images.busybox" $ }}
        imagePullPolicy: {{ include "common.images.defaultPullPolicy" $ }}
        command: ["sh", "-c"]
        args:
        - |
          cp /root/sss_keytab/input/maintd.keytab /root/sss_keytab/output/cta-maintd.sss.keytab;
          chmod 400 /root/sss_keytab/output/cta-maintd.sss.keytab;
          # Make CTA user owner (group 33 is tape)
          chown -R 1000:33 /root/sss_keytab/output/cta-maintd.sss.keytab
        volumeMounts:
          - name: maintd-sss-keytab
            mountPath: /root/sss_keytab/input/maintd.keytab
            subPath: {{ $.Values.keytab.subPath }}
          - name: maintd-sss-keytab-fixedownership
            mountPath: /root/sss_keytab/output
      containers:
      - name: cta-maintd
        image: {{ include "maintd.image" $ }}
        imagePullPolicy: {{ include "maintd.imagePullPolicy" $ }}
        stdin: true
        command: ["/bin/bash", "-c"]
        args: ["{{- if $.Values.preRun.enabled }}/scripts/pre_run.sh;{{- end }} /scripts/maintd.sh; {{- if $.Values.postRun.enabled }}/scripts/post_run.sh;{{- end }}"]
        startupProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: {{ include "common.securityContext.allowPrivilegeEscalation" $ }}
          privileged: {{ include "common.securityContext.privileged" $ }}
          capabilities:
            add: ["SYS_PTRACE"]
        env:
        - name: MY_NAME
          value: {{ $podName }}
        - name: MY_NAMESPACE
          value: {{ $.Release.Namespace | quote }}
        - name: INSTANCE_NAME
          value: {{ $.Release.Namespace | quote }}
        - name: TERM
          value: "xterm"
        - name: SCHEDULER_BACKEND
          value: {{ $schedulerConfig.backend | quote }}
        {{- with $.Values.extraEnv }}
        {{- include "common.extraEnv" . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
        - name: cta-maintd-config
          mountPath: /etc/cta/cta-maintd.toml
          subPath: cta-maintd.conf
        - name: catalogue-config
          mountPath: /etc/cta/cta-catalogue.conf
          subPath: cta-catalogue.conf
        - name: maintd-sss-keytab-fixedownership
          mountPath: /etc/cta/cta-maintd.sss.keytab
          subPath: cta-maintd.sss.keytab
        {{- if eq $schedulerConfig.backend "postgres" }}
        - name: scheduler-config
          mountPath: /etc/cta/cta-scheduler.conf
          subPath: cta-scheduler.conf
        {{- else if eq $schedulerConfig.backend "ceph" }}
        - name: cta-ceph-volume
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
        - name: cta-ceph-volume
          mountPath: /etc/ceph/ceph.client.{{ $schedulerConfig.cephConfig.id }}.keyring
          subPath: ceph.client.{{ $schedulerConfig.cephConfig.id }}.keyring
        {{- end }}
        {{- if $.Values.global.volumeMounts }}
        {{ $.Values.global.volumeMounts | toYaml | nindent 8 }}
        {{- end }}
        - name: opentelemetry-config
          mountPath: /etc/cta/cta-otel.yaml
          subPath: cta-otel.yaml
      {{- if eq $schedulerConfig.backend "vfs" }}
        - name: vfs-storage-volume
          mountPath: /objectstore
      {{- end }}
        {{ include "common.extraVolumeMounts" $ | nindent 8 }}
      volumes:
      - name: scripts-volume
        configMap:
          name: scripts-maintd
          defaultMode: 0777
      - name: catalogue-config
        configMap:
          name: cta-catalogue-conf
      {{- if eq $schedulerConfig.backend "postgres" }}
      - name: scheduler-config
        configMap:
          name: cta-scheduler-conf
      {{- else }}
      - name: scheduler-config
        configMap:
          name: cta-objectstore-conf
      {{- end }}
      {{- if eq $schedulerConfig.backend "ceph" }}
      - name: cta-ceph-volume
        configMap:
          name: ceph-conf
      {{- end }}
      {{- if eq $schedulerConfig.backend "vfs" }}
      - name: vfs-storage-volume
        persistentVolumeClaim:
          claimName: scheduler-vfs-pvc
      {{- end }}
      - name: cta-maintd-config
        configMap:
          name: cta-maintd-{{ $routineNameSlug }}-conf
      - name: opentelemetry-config
        configMap:
          name: cta-maintd-otel-conf
      - name: maintd-sss-keytab
        secret:
          secretName: {{ $.Values.keytab.secretName }}
      - name: maintd-sss-keytab-fixedownership
        emptyDir: {}
      {{- if $.Values.global.volumes }}
      {{ $.Values.global.volumes | toYaml | nindent 6 }}
      {{- end }}
      {{ include "common.extraVolumes" $ | nindent 6 }}
---
{{- end }}
{{- end }}
