{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-rmcd
data:
  rmcd.sh: |
    {{ .Files.Get "scripts/rmcd.sh" | nindent 4 }}
  pre_run.sh: {{ .Values.preRun.script | toYaml | nindent 4 }}
  post_run.sh: {{ .Values.postRun.script | toYaml | nindent 4 }}
