# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

extraScrapeConfigs: |
  - job_name: "otel-collector"
    static_configs:
      - targets:
        - otel-opentelemetry-collector:8889

rbac:
  create: true

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true

# We want to get metrics on CPU/memory usage
prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false

server:
  global:
    scrape_interval: 15s
    scrape_timeout: 3s

  persistentVolume:
    enabled: false
