# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# Helm performs a merge, so we cannot just overwrite the entire routines object from the base maintd chart
# Any routines specific here, will run IN ADDITION TO whatever is specified in the values.yaml of the maintd chart
maintd:
  routines:
    garbageCollect:
      replicas: 1
      sleepInterval: 1000
    queueCleanup:
      replicas: 1
      sleepInterval: 1000
      batchSize: 500

# The remainder of the values are inherited from the default values.yaml
