# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

maintd:
  routines:
    # Note that the snake_case version of all these options (including the names)
    # should match the corresponding names in the maintd conf file
    # So diskReportArchive:softTimeout will map to cta.routines.disk_report_archive.soft_timeout
    # To disable a routine, set replicas to 0
    diskReportArchive:
      replicas: 2
      sleepInterval: 1000
      batchSize: 500
      softTimeout: 30
    diskReportRetrieve:
      replicas: 2
      sleepInterval: 1000
      batchSize: 500
      softTimeout: 30
    repackExpand:
      replicas: 1
      sleepInterval: 1000
      maxToToExpand: 2
    repackReport:
      replicas: 1
      sleepInterval: 1000
      softTimeout: 30

    # Note that these routines are different from the objectstore values
    userActiveQueueCleanup:
      replicas: 1
      sleepInterval: 900000
      batchSize: 1000
      ageForCollection: 1800
    repackActiveQueueCleanup:
      replicas: 1
      sleepInterval: 900000
      batchSize: 1000
      ageForCollection: 1800
    userPendingQueueCleanup:
      replicas: 1
      sleepInterval: 60000
      batchSize: 1000
      ageForCollection: 120
    repackPendingQueueCleanup:
      replicas: 1
      sleepInterval: 60000
      batchSize: 1000
      ageForCollection: 120
    schedulerMaintenanceCleanup:
      replicas: 1
      sleepInterval: 86400000
      batchSize: 1000
      ageForDeletion: 1209600

  # The remainder of the values are inherited from the default values.yaml
