{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- if .Values.grpc.enabled }}
{{- $schedulerConfig := include "scheduler.config" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cta-frontend-grpc-conf
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  cta-frontend-grpc.conf: |-
    #
    # CTA options
    #

    cta.instance_name {{ .Release.Namespace }}
    cta.schedulerdb.scheduler_backend_name {{ $schedulerConfig.backend }}

    # CTA ObjectStore options
    cta.objectstore.backendpath {{ include "global.schedulerUrl" . }}

    # CTA Scheduler DB options
    cta.schedulerdb.numberofthreads {{ .Values.grpc.conf.schedulerdb.numberOfThreads }}
    cta.schedulerdb.threadstacksize_mb {{ .Values.grpc.conf.schedulerdb.threadStackSizeMb }}
    cta.schedulerdb.disable_repack_requests {{ .Values.grpc.conf.schedulerdb.disableRepackRequests }}
    cta.schedulerdb.disable_user_requests {{ .Values.grpc.conf.schedulerdb.disableUserRequests }}

    # CTA Scheduler DB options - Cache timeout options (decreased for tests)
    cta.schedulerdb.tape_cache_max_age_secs {{ .Values.grpc.conf.schedulerdb.tapeCacheMaxAgeSecs }}
    cta.schedulerdb.retrieve_queue_cache_max_age_secs {{ .Values.grpc.conf.schedulerdb.retrieveQueueCacheMaxAgeSecs }}

    # CTA Catalogue options
    cta.catalogue.numberofconnections {{ .Values.grpc.conf.catalogue.numberOfConnections }}

    # Missing tape file copies minimum age.
    # Set it to prevent false flagging of multi-copy files in the process of being archived tapes.
    # Default 24 hours
    cta.catalogue.missing_file_copies_min_age_secs {{ .Values.grpc.conf.catalogue.missingFileCopiesMinAgeSecs }}

    # Maximum file size (in GB) that the CTA Frontend will accept for archiving
    cta.archivefile.max_size_gb {{ .Values.grpc.conf.frontend.archiveFileMaxSizeGb }}

    # Disallow 0-length files
    cta.archivefile.zero_length_files_forbidden {{ .Values.grpc.conf.frontend.zeroLengthFilesForbidden }}

    # Tapepools exempted from this check (if enabled)
    cta.archivefile.zero_length_files_forbidden_vo_exception_list {{ .Values.grpc.conf.frontend.zeroLengthFilesForbiddenVoExceptionList }}

    # CTA Frontend log URL
    cta.log.url file:/var/log/cta/cta-frontend-grpc.log

    # CTA Logger log level
    # Valid log levels are EMERG, ALERT, CRIT, ERR, WARNING, NOTICE (==USERERR), INFO, DEBUG
    cta.log.level {{ .Values.grpc.conf.logger.logLevel }}

    # CTA Logger log format
    # Valid formats are default, json
    cta.log.format {{ .Values.grpc.conf.logger.logFormat }}

    cta.log.log_header true

    # CTA Repack buffer URL
    # cta.repack.repack_buffer_url {{ .Values.grpc.conf.frontend.repackBufferUrl }}

    # CTA Verification Mount Policy
    cta.verification.mount_policy verification

    # gRPC options
    grpc.port {{ .Values.grpc.port }}
    grpc.numberofthreads {{ .Values.grpc.conf.numberOfThreads }}

    # TLS related variables
    grpc.tls.enabled {{ .Values.grpc.conf.tls.enabled }}
    grpc.tls.server_key_path {{ .Values.grpc.conf.tls.serverKey }}
    grpc.tls.server_cert_path {{ .Values.grpc.conf.tls.serverCert }}
    grpc.jwks.uri {{ .Values.grpc.conf.jwtAuth.jwksUri }}
    grpc.jwt.enabled {{ .Values.grpc.conf.jwtAuth.enabled }}

    # for the admin commands
    cta.experimental.grpc.cta_admin_commands.enabled {{ .Values.grpc.conf.experimental.ctaAdminCommands.enabled }}

    # Telemetry
    cta.experimental.telemetry.enabled {{ .Values.grpc.conf.telemetry.enabled }}

    cta.telemetry.retain_instance_id_on_restart {{ .Values.grpc.conf.telemetry.retainInstanceIdOnRestart }}
    cta.telemetry.metrics.backend {{ .Values.grpc.conf.telemetry.metrics.backend }}
    {{- if .Values.grpc.conf.telemetry.metrics.exportInterval }}
    cta.telemetry.metrics.export.interval {{ .Values.grpc.conf.telemetry.metrics.exportInterval }}
    {{- end }}
    {{- if .Values.grpc.conf.telemetry.metrics.exportTimeout }}
    cta.telemetry.metrics.export.timeout {{ .Values.grpc.conf.telemetry.metrics.exportTimeout }}
    {{- end }}
    {{- if .Values.grpc.conf.telemetry.metrics.otlp.endpoint }}
    cta.telemetry.metrics.otlp.endpoint {{ .Values.grpc.conf.telemetry.metrics.otlp.endpoint }}
    {{- end }}
    {{- if .Values.grpc.conf.telemetry.metrics.otlp.auth.basic.username }}
    cta.telemetry.metrics.otlp.auth.basic.username {{ $.Values.grpc.conf.telemetry.metrics.otlp.auth.basic.username }}
    {{- end }}
    {{- if .Values.grpc.conf.telemetry.metrics.otlp.auth.basic.passwordSecret }}
    cta.telemetry.metrics.otlp.auth.basic.password_file /etc/cta/otlp-basic-auth-pwd.conf
    {{- end }}
    {{- if .Values.grpc.conf.telemetry.metrics.file.endpoint }}
    cta.telemetry.metrics.file.endpoint {{ .Values.grpc.conf.telemetry.metrics.file.endpoint }}
    {{- end }}

    # Kerberos authentication
    grpc.keytab {{ .Values.grpc.keytab }}
    grpc.service_principal {{ .Values.grpc.service_principal }}
    grpc.adm.auth.protocols jwt
{{- end }}
