# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: v2
name: scheduler
version: 0.1.0
description: A chart that sets up a configmap for the scheduler and optionally a postgres pod.
type: application
appVersion: "5.11.10.1"

dependencies:
  - name: common
    version: 0.1.1
    repository: "file://../common"
