# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

resetScheduler: false

resetImage:
  repository: gitlab-registry.cern.ch/cta/ctageneric
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets:
    - reg-ctageneric

# configuration:
#   backend: "" # Options: vfs, vfsDeprecated ceph, postgres
#   cephConfig:
#     mon: ""
#     monport: ""
#     pool: ""
#     namespace: ""
#     id: ""
#     key: ""
#   postgresConfig:
#     username: ""
#     password: ""
#     database: ""
#     server: ""
#   vfsConfig:
#     storageClass: ""
#     annotations: {}
#     accessModes:
#       - ReadWriteOnce
#     size: 20Gi
#   vfsDeprecated Config:
#     path: ""

# This is only for the postgres pod
pod:
  extraSpec:
    # We want to know if something went wrong in CI
    restartPolicy: Never
