{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- $schedulerConfig := include "scheduler.config" . | fromYaml }}
{{- if and (eq $schedulerConfig.backend "postgres") (not $schedulerConfig.postgresConfig.remote) }}
{{- $name := include "schedulerPostgres.fullname" . }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  {{- if .Values.pod.extraSpec }}
  {{ .Values.pod.extraSpec | toYaml | nindent 2 }}
  {{- end }}
  containers:
  - name: cta-scheduler-postgres
    image: docker.io/postgres:14.10
    ports:
      - containerPort: 5432
    stdin: true
    command: []
    args: []
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - >
          pg_isready -U {{ $schedulerConfig.postgresConfig.username }} -d {{ $schedulerConfig.postgresConfig.database }} -h 127.0.0.1 -p 5432
      initialDelaySeconds: 0
      periodSeconds: 2
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 20
    securityContext:
      allowPrivilegeEscalation: false
    {{- if $.Values.resources }}
    resources:
      {{-  toYaml $.Values.resources | nindent 10 }}
    {{- end }}
    env:
    - name: MY_NAME
      value: {{ $name }}
    - name: MY_NAMESPACE
      value: {{ .Release.Namespace | quote }}
    - name: INSTANCE_NAME
      value: {{ .Release.Namespace | quote }}
    - name: PGDATA
      value: {{ $schedulerConfig.postgresConfig.path }}
    - name: POSTGRES_USER
      value: {{ $schedulerConfig.postgresConfig.username }}
    - name: POSTGRES_PASSWORD
      value: {{ $schedulerConfig.postgresConfig.password }}
    - name: POSTGRES_DB
      value: {{ $schedulerConfig.postgresConfig.database }}
    - name: POSTGRES_INITDB_ARGS
      value: "--no-locale --encoding=UTF8"
{{- end }}
