apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-cta-ctacli
  labels:
    app.kubernetes.io/name: {{ include "ctacli.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: ctacli
    app.kubernetes.io/part-of: {{ .Values.partOf | default "cta" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  cta-cli.conf: |-
    # solved by kubernetes DNS server so KIS...
    cta.endpoint {{ .Values.conf.cta.endpoint }}
    eos.instance {{ .Values.conf.eos.instance }}
    eos.requester.user {{ .Values.conf.eos.requester.user }}
    eos.requester.group {{ .Values.conf.eos.requester.group }}
