# See https://monit.docs.cern.ch/other/metrics/

# Note that this values can be used in combination with other values files
frontend:
  xrd:
    conf:
      telemetry:
        enabled: false
        retainInstanceIdOnRestart: false
        metricsBackend: "OTLP_GRPC"
        metricsExportOtlpEndpoint: "https://monit-otlp.cern.ch:4316"
        metricsExportOtlpBasicAuthSecret: monit-collector-auth

  grpc:
    conf:
      telemetry:
        enabled: false
        retainInstanceIdOnRestart: false
        metricsBackend: "OTLP_GRPC"
        metricsExportOtlpEndpoint: "https://monit-otlp.cern.ch:4316"
        metricsExportOtlpBasicAuthSecret: monit-collector-auth

tpsrv:
  conf:
    telemetry:
      enabled: false
      retainInstanceIdOnRestart: true
      metricsBackend: "OTLP_GRPC"
      metricsExportOtlpEndpoint: "https://monit-otlp.cern.ch:4316"
      metricsExportOtlpBasicAuthSecret: monit-collector-auth
