apiVersion: v2
name: client
description: A Client helm chart for Kubernetes in CTA project. Sets up a client pod and a service with defined configuration in values.yaml file.
type: application
version: 0.1.0
appVersion: "1.16.0"
