# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

keycloak:
  image: registry.cern.ch/quay.io/keycloak/keycloak:26.1
  adminUsername: admin
  adminPassword: admin
  realm: master
  accessTokenLifespan: 36000
  ssoSessionMaxLifespan: 36000

kerberos:
  image: registry.cern.ch/docker.io/almalinux/9-minimal:9.7
  defaultRealm: TEST.CTA
  adminPrinc:
    name: root
    password: "defaultcipassword"
