# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

component: kdc
partOf: auth

image:
  repository: gitlab-registry.cern.ch/cta/ctageneric
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets:
    - reg-ctageneric

keycloak:
  image: registry.cern.ch/quay.io/keycloak/keycloak:26.1
  adminUsername: admin
  adminPassword: admin
  realm: master
  accessTokenLifespan: 36000
  ssoSessionMaxLifespan: 36000

kerberos:
  defaultRealm: TEST.CTA
  adminPrinc:
    name: root
    password: "defaultcipassword"

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1  # This is low on purpose as the current process has no gracefull shutdown process

# Additional Extra environment variables
extraEnv:
