# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

replicaCount: 1
useGrpc: false

conf:
  cta:
    endpoint: cta-frontend:10955

krb5PrincName: ctaadmin1

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1

# Additional Extra environment variables
extraEnv:

extraVolumes:
  volumes:
    - name: grpc-certs
      secret:
        secretName: ca-crt
  volumeMounts:
    - name: grpc-certs
      mountPath: /etc/grpc-certs
      readOnly: true
