# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

[tests]

krb5_realm = "TEST.CTA"

[tests.stress]

# For the actual stress test we currently have 40 directories with 50.000 files each
# mhvtl is mounted in-memory, so we keep the file size small and easily compressible (unique string + zero padding)
num_dirs = 10
num_files_per_dir = 1000
file_size = 512
io_threads = 8

[tests.stress.prequeue]

# If true, put drives down before archiving and only put them up after num_files_to_put_drives_up files are created.
# This prevents drives from outpacing the queueing capabilities of EOS.
prequeue = true
num_files_to_put_drives_up = 5000
# timeout in seconds
timeout_to_put_drives_up = 3600
check_every_sec = 10
