# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

[tests]

krb5_realm = "TEST.CTA"

[tests.stress]

num_dirs = 10
num_files_per_dir = 1000
file_size = 512
io_threads = 8
