# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: v2
name: cta
description: Umbrella chart that spawns a fully fledged CTA instance. Requires a disk buffer instance to be spawned separately.
type: application
version: 0.2.0
appVersion: "5.11.10.1"

dependencies:
- name: frontend
  repository: "file://../frontend"
  version: 0.2.0
- name: cli
  repository: "file://../cli"
  version: 0.2.0
- name: client
  repository: "file://../client"
  version: 0.2.0
- name: tpsrv
  repository: "file://../tpsrv"
  version: 0.2.0
- name: maintd
  repository: "file://../maintd"
  version: 0.2.0
