apiVersion: v2
name: cta
description: A CTA helmchart for CI runner. On itself it only contains configmaps that are used in every other subchart
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: ctafrontend
  alias: ctafrontend
  version: 0.1.0
- name: ctacli
  alias: ctacli
  version: 0.1.0
- name: client
  alias: client
  version: 0.1.0
- name: tpsrv
  alias: tpsrv
  version: 0.1.0
- name: ctaeos
  alias: ctaeos
  version: 0.1.0