{{- if eq .Values.global.catalogue.backend "postgres" -}}
{{$namespace := .Release.Namespace }}
{{$name := "postgres" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  clusterIP: None
  ports:
    - name: {{ $name }}
      port: {{ .Values.servicePort }}
      protocol: TCP
{{- end }}
