{{$namespace := .Release.Namespace }}
{{- with .Values.serviceAccount}}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ printf "%s-%s" .name "role" }}
rules:
    {{- .rules | toYaml | nindent 2}}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.name}}
  namespace: {{$namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" .name "roleBinding" }}
  namespace: {{$namespace}}
subjects:
- kind: ServiceAccount
  name: {{.name}}
roleRef:
  kind: Role
  name: {{ printf "%s-%s" .name "role" }}
  apiGroup: rbac.authorization.k8s.io
{{- end}}