# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

image:
  repository: gitlab-registry.cern.ch/cta/eoscta-operations/registry/container_registry/cta-catalogue-updater
  tag: "alma9-base.1"
  pullPolicy: IfNotPresent
  pullSecrets:
    - reg-eoscta-operations

catalogueSourceVersion: ""

catalogueDestinationVersion: ""

# Additional Extra environment variables
extraEnv:

# Set to true if you want to mount the configmap "yum.repos.d-config"
customRepoFiles: true
